### ISSUE TITLE
CD53 UI Documentation

### ISSUE THREAD

**Issue by dutchhome** [tedsalmon/BlueBus#1]
Here are some notes I put together for the CD53 UI. Maybe it will help with the documentation?

CD53
====

Button 1: Play / Pause
Button 2: Unknown
Button 3: Unknown
Button 4: Unknown
Button 5: Shows BT device name (* = connected)
Button 6: Pairing on / off
Left action button (RND): Random mode
Right action button <blank>: Unknown
Left triangle: Previous track
M Button: Manual mode
Right triangle: Next track

Notes:
* BlueBus will automatically pause the music source when the radio is turned off
* When turning on pairing mode, any existing Bluetooth connection is terminated
* Manual mode does not work. While in manual mode, prev / next track buttons do nothing
* RND currently turns on but can't be turned off.  When on, prev / next track buttons do nothing

**Comment by tedsalmon** [comment]
Moved to the Wiki, here: https://github.com/tedsalmon/BlueBus/wiki/CD53-UI

Thanks, @dutchhome
