### ISSUE TITLE
Cannot enter UI on E85/Board Monitor

### ISSUE THREAD

**Issue by Magsybaby** [tedsalmon/BlueBus#100]
Sorry if I am doing something dumb, I have been using it for over a year without issue but I now have a new phone. This has shown I can't actually enter the menu and pressing 6 for pairing is not working. I swear when I installed it that it was working.

UK - 2003 - E85 Z4 - Nav, DSP, TV, Tel. DSP is digital but connected analog. I am not using BlueBus telephony.

I have flashed the latest firmware release but it has not changed.

https://www.youtube.com/watch?v=owfGUS8Lnw4

Thanks :)

**Comment by tedsalmon** [comment]
@Magsybaby

Please press the knob on the right once to exit the dashboard. From there, Navigate to "Devices" in the new menu and you'll be able to pair a new phone. The 1 - 6 buttons are not used on the Navigation UI, FWIW ;)
