### ISSUE TITLE
E83 X3 - Conflict with factory(?) satellite radio

### ISSUE THREAD

**Issue by ryannoblett** [tedsalmon/BlueBus#107]
I have a 2007 X3 3.0si with factory(?) satellite radio (2006 build date). I installed the bluebus and disconnected the TCU, but I'm unable to locate a satellite radio module - it's not in the trunk area where I expected it. The bluebus sort of works, I can receive phone calls, and if I mess with the buttons for a bit, I can get into the menu (with glitches), but can't play music and only hear the satellite radio demo channel. Also, the comfort blinkers don't work, etc.

My assumption is that I need to remove or disable the satellite radio somehow. Is this correct?

If so, does anyone know where the satellite radio module is on this model? I've been unsuccessful in locating it. It's not in the driver side trunk area with the TCU and navigation DVD drive like it is on most other models. I also checked under the cargo floor area.

Thanks for your assistance.

**Comment by tedsalmon** [comment]
@ryannoblett

Can you describe the menu "glitches"? This vehicle is equipped with Navigation, correct?

>My assumption is that I need to remove or disable the satellite radio somehow. Is this correct?
Not entirely. You can if you don't want it, or you could use the slave cable: https://www.ecstuning.com/b-genuine-bmw-parts/sirius-slave-cable/84110150526/?

Of course, you'd have to find the Sirius module first. I do believe it should be in the rear driver side electronics bay, along with the Navi and other modules.

Did you install the BlueBus in that area as well? Any pictures of how it's installed? Typically these cars had the CD Changer installed in the center console, which is why I'm asking.

It may also be easier to reach me by email: support@bluebus.dev

-Ted

**Comment by ryannoblett** [comment]
Yes, it's got navigation. When I say glitches, sometimes the text in the bluebus menus get overwritten by other text I assume is from the satellite radio module. I wasn't able to capture that well, so I hope the description is good enough.

I did install the bluebus in the driver's side trunk area with the navigation drive and TCU. I'm attaching some pictures, and I'll link to a video trying to use the bluebus, but hearing the satellite radio instead.

Video: https://pics.deadface.org/phone/x3/bluebus/VID_20211227_194148.mp4

![amp](https://user-images.githubusercontent.com/23060576/147526544-bb8bdca9-f41e-4463-a77a-deffa851713a.jpg)
![bluebus](https://user-images.githubusercontent.com/23060576/147526545-db0d0ced-7bb6-459b-b899-f0ce437700d8.jpg)
![nav](https://user-images.githubusercontent.com/23060576/147526547-2007dd00-d72f-41e9-902b-64309867759e.jpg)
![tcu](https://user-images.githubusercontent.com/23060576/147526549-dc90270e-94f0-4de9-bfbc-a475deee4fc8.jpg)

Thanks again for your help.

**Comment by E39NLA** [comment]
Following this thread as I also have an E38 X3.

I think you may have the Bluebus connected wrong. According to TIS, an X3 with Sat, Nav, and DSP should use the 6-pin CD-SDARS connector. As Ted mentioned, the CD changer on these cars lived in the center console box, not the rear equipment compartment. You might find that connector there. See attached.
![PXL_20230324_201918354](https://user-images.githubusercontent.com/73809282/227631781-af20b6cb-96f7-40d2-8056-61afdc9d4cc3.jpg)

**Comment by ryannoblett** [comment]
Thanks for sharing this info, turns out it's exactly what I needed. I pulled the tray out of my center console to find both an aftermarket Sirius satellite module and a Dice Mediabridge!
![IMG20230324185257](https://user-images.githubusercontent.com/23060576/227657469-b9e82cb1-8b28-4a8b-ab3b-4f0fe87abdc8.jpg)
![IMG20230324185311](https://user-images.githubusercontent.com/23060576/227657520-46cf0642-cfc7-47f9-b8b7-ba0f30137450.jpg)
I'll get this stuff out and see what it takes to get the bluebus going.

**Comment by ryannoblett** [comment]
So, partial success - the bluebus plays music perfectly when plugged into the CD changer connectors in the center console.
![IMG20230324194145](https://user-images.githubusercontent.com/23060576/227662842-7b1ba880-ce98-4732-843b-a4ea8ba66f4f.jpg)
![IMG20230324194240](https://user-images.githubusercontent.com/23060576/227662846-0a667aae-8a98-4af0-9b37-4c71716f0ccd.jpg)
However, there is no way to connect it to the TCU adapter plug, which is in the trunk area. I think I will have to make an extension cable and run it back there to get Bluetooth calls working again. Unfortunately, even with the Sirius and dice Mediabridge disconnected, it still does not work correctly using the connectors I'm the trunk area.

**Comment by ryannoblett** [comment]
Thanks Ted, switching that cable made it work in the rear and now it's fully functional.
