### ISSUE TITLE
Request: CD53 - Disable Metadata

### ISSUE THREAD

**Issue by stryd3r99** [tedsalmon/BlueBus#115]
Possible to include an option to disable metadata.  With such a small screen on the CD53, it is very distracting to have media data scroll across the screen.

**Comment by tedsalmon** [comment]
Hitting the "2" will disable metadata scrolling :)

**Comment by tedsalmon** [comment]
> Yes, hitting "2" disables the scrolling and then you can press the clock to not show the remaining metadata.  But this has to be done each and every time you restart the car.  Hoping there can be a simple way to disable the metadata.  On Monday, June 20, 2022, 11:29:16 AM PDT, Ted Salmon ***@***.***> wrote: Hitting the "2" will disable metadata scrolling :) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

I'll get this sorted in 1.1.19, which I hope to drop next week.

**Comment by stryd3r99** [comment]
Awesome!  Thanks Ted!!!

________________________________

**Comment by tedsalmon** [comment]
@stryd3r99 

This has been implemented in firmware version 1.3.0 which is now available on the website :) 

https://www.bluebus.dev/software

**Comment by stryd3r99** [comment]
Thank you!
    On Wednesday, October 5, 2022 at 04:19:06 PM PDT, Ted Salmon ***@***.***> wrote:  
 
 


Closed #115 as completed.

**Comment by stryd3r99** [comment]
This weekend I installed firmware v1.3.0.  I can confirm that I see the three separate options for the metadata: chunk, party, disabled.  I can also set the metadata to disabled and save the setting. 
Unfortunately, there is no change in metadata behavior.  It still displays.  Any suggestions on how to troubleshoot?




    On Wednesday, October 5, 2022 at 05:03:41 PM PDT, Mauricio Lopez-Hodoyan ***@***.***> wrote:  
 
  Thank you!
    On Wednesday, October 5, 2022 at 04:19:06 PM PDT, Ted Salmon ***@***.***> wrote:  
 
 


Closed #115 as completed.

**Comment by stryd3r99** [comment]
Hi Ted, want to report a bug with disabling meta data.  I have firmware version 1.3.0 installed and can confirm that the disable metadata option is available in the settings menu.  
However, turning metadata off doesn't actually do anything.  The metadata is still displayed regardless of setting.  Is there a separate option I need to enable?  
Thanks,
Mauricio


    On Wednesday, October 5, 2022 at 04:19:06 PM PDT, Ted Salmon ***@***.***> wrote:  
 
 


@stryd3r99

This has been implemented in firmware version 1.3.0 which is now available on the website :)

https://www.bluebus.dev/software

**Comment by stryd3r99** [comment]
Hi Ted, following up on the "Disable Metadata" feature request.  
The option to disable metadata is present in firmware v1.3.0, however, setting the bluebus to hide metadata doesn't actually do anything.   Is ther a newer version of the sofware that has the hide metadata feature implemented correctly?  
Sorry for the late feedback on this.  I installed the updated firmware back in October and never got around to providing you with feedback.  

Thanks,
p.s. The bluebus is a great product!  My 3-series is a daily driver and I use the bluebus every day.  


    On Wednesday, October 5, 2022 at 04:19:06 PM PDT, Ted Salmon ***@***.***> wrote:  
 
 


@stryd3r99

This has been implemented in firmware version 1.3.0 which is now available on the website :)

https://www.bluebus.dev/software
