### ISSUE TITLE
Improvement: Dynamic Bluetooth device name depending on vehicle type

### ISSUE THREAD

**Issue by multilan-tarek** [tedsalmon/BlueBus#118]
I have a little improvement idea: Dynamic Bluetooth device name depending on the vehicle type.

For example in a 5 Series E39: _BMW 5 Series_
or in a 3 Series E46: _BMW 3 Series_
... something like that.

Perhaps the last 3 digits of the VIN would also be nice as a unique identifier at the end.
For example:
_BMW 5 Series 757_ or _BMW 5 Series (757)_

I hope that I have expressed that understandably. English isn't my primary language.
Greetings from Germany! :)

**Comment by tedsalmon** [comment]
Thanks for the request @multilan-tarek!

While it's somewhat possible to implement what you're requesting, it's definitely a little more difficult than you may imagine. The clusters found in the E38, E39 and E53 are all shared across platforms and are impossible to distinguish. If the vehicle has Navigation, then the chassis can be pulled off the coding data of the Graphics Terminal, though.

However, I'm not sure it's entirely useful to distinguish the Bluetooth GAP Advertised name, and it might create confusion for those who expect the name to be "BlueBus" as that is the product name. 

You can already alter the name via Terminal if you wish using the `bt name` command.

Thanks for your time!
-Ted
