### ISSUE TITLE
After udating the BlueBus cant be found

### ISSUE THREAD

**Issue by Futzemann** [tedsalmon/BlueBus#120]
I flashed the firmware ‚Bluebus_1_0_0.hex. The Flash completed ..

but now the ‚Firmware Tool' doesn’t find the BlueBus...

I see the BlueBus in the select DropDown menu, but 5 sec Error is popping up

It can’t be the cable (I think), because the first flash was complete..

So what could be the issue here??

**Comment by tedsalmon** [comment]
The issue here was a failed firmware load. Per our email, recovery mode was used to restore functionality :)
