### ISSUE TITLE
Windows upgrade tool link is broken

### ISSUE THREAD

**Issue by ShonkyCH** [tedsalmon/BlueBus#121]
https://github.com/tedsalmon/BlueBus/wiki/Firmware-Upgrade link for the 64 bit Windows tool gives

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>BlueBus/BlueBus_Firmware_Tool.exe</Key>
<RequestId>TSXYBFZQGV63B9EK</RequestId>
<HostId>4XKuEWruh2dCoO1bw58OXpMLVYtGlO6d6LED/ujbc0J4fgx/J0skVozWUuzB7U411/JvX7WZmaI=</HostId>
</Error>
```

MacOS and Linux versions are OK.

**Comment by tedsalmon** [comment]
Thanks @ShonkyCH! I deleted it from S3 because I came up with an updated version. I have updated the link :)
