### ISSUE TITLE
Firmware 1.3.0

### ISSUE THREAD

**Issue by socoolbreeze** [tedsalmon/BlueBus#125]
What a nice release.
Looks very stable and nice new features. Love it.

-Length with DASH OBC temps is still to long for my device I think.
The right temp has a+ symbol at the end without any numbers with value
Maybe naming it from Temp ℃ to just ℃ gives a clean and same result.
O:91 C:80 A:10 ℃
or: ℃ O:91 C:80 A:10 ℃
i like te arrange it from low to high:
TEMP: A:10 C: 80 O:91  ℃

or if possible on the right side of the screen?!
from top every line with info
Ambient:
Coolant:
Oil:

![IMG_9077](https://user-images.githubusercontent.com/74147080/195852090-ed3b6fd1-1e88-476d-be5d-ac84b45c3fba.jpeg)

-BMBT ON
When activated I cannot turn the screen on at any time.
![homebutton](https://user-images.githubusercontent.com/74147080/195540828-67b50800-8019-4f2a-bbf0-8eca3ab7ba9e.jpeg)
Maybe possible to do with the standard button?

-Translation updates (now and future release)
With dutch translation the new features aren't translated. Where and how can I update it, for now, and pre-release new features?
Also the functions labels are in the wrong place so probably a mixup within upgrading from old translation to new with new to translate rules.

**Comment by nabucho** [comment]
Hi @socoolbreeze , thanks for test and screenshot. 

As for translations - easiest would be to look directly at https://github.com/tedsalmon/BlueBus/blob/master/firmware/application/lib/locale.c there is an "Edit" button. Try to find / update the localization there. Do not change order, do not add lines, delete lines. (Other than making sure the order for same labels is exactly the same as ENGLISH texts). Than fill in "Propose change" there there, name the branch eg dutch-locale-1.3.0 for Ted or me to test/merge/compile into next release. 

What do you mean by "function labels" please?

As for the temperatures, will look at this, I hoped to have it shortened before, but might got lost along the way. One option I personally like, is having one temp in headers - eg. outside temp in the top header beside Bluetooth and phone name, and only the remaining two in the line in Dashboard. Would that be OK? 
With the right part of the screen, actually, it is not available always, so that may not be viable solution.

**Comment by socoolbreeze** [comment]
> Hi @socoolbreeze , thanks for test and screenshot.
> 
> As for translations - easiest would be to look directly at https://github.com/tedsalmon/BlueBus/blob/master/firmware/application/lib/locale.c there is an "Edit" button. Try to find / update the localization there. Do not change order, do not add lines, delete lines. (Other than making sure the order for same labels is exactly the same as ENGLISH texts). Than fill in "Propose change" there there, name the branch eg dutch-locale-1.3.0 for Ted or me to test/merge/compile into next release.
> 
> What do you mean by "function labels" please?
> 
> As for the temperatures, will look at this, I hoped to have it shortened before, but might got lost along the way. One option I personally like, is having one temp in headers - eg. outside temp in the top header beside Bluetooth and phone name, and only the remaining two in the line in Dashboard. Would that be OK? With the right part of the screen, actually, it is not available always, so that may not be viable solution.
> 
> <img alt="Screenshot 2022-10-18 at 15 32 24" width="1331" src="https://user-images.githubusercontent.com/192888/196460714-84ddc186-f068-4ad1-8f27-4327f0e9878d.png">
> 
> <img alt="Screenshot 2022-10-18 at 15 34 04" width="714" src="https://user-images.githubusercontent.com/192888/196460723-9790fd41-78fa-4a7c-882d-28fefd235814.png">

Thanks for the reply. I just updated the language. And wil do in future release like this. Works great.
The function labels I meant like. Every label function like, dashboard or comfort settings where on different places. Probably because of an extra line of code or something. Hope now is the same order and the same amount it will show everything on the right place.

As for the mgmt I hope we can turn the screen on when standing still with car for lights or parking or wondering what song it is. Thanks for the help and temperature fix.
For me I like it al in one place. But actually you can make it how you want it. I don't have the skill to code like I want it ;)

**Comment by nabucho** [comment]
Thanks. The shifted labels have been fixed.

Have you saved / proposed your changes in the Localization file? Cannot see it.

**Comment by socoolbreeze** [comment]
https://github.com/tedsalmon/BlueBus/compare/master...socoolbreeze:BlueBus:patch-1

This is where I can see the changes. I'm very new at this. If I have to
redo it please let me know.

greetz Ben

Op di 18 okt. 2022 om 16:32 schreef Ivan Debnar ***@***.***>:

**Comment by nabucho** [comment]
Amazing! Thanks, I merged it into fix/1.3.1 branch, so it will be included in next release. Or if you want to try, I can send you a .hex file with the updates.

**Comment by socoolbreeze** [comment]
Ow thanks yeah that would be great if you can shoot me a hex file of the
1.3.1!
many thanks

gr Ben

Op ma 31 okt. 2022 om 23:39 schreef Ivan Debnar ***@***.***>:

**Comment by nabucho** [comment]
Send me an email - address in my profile.

**Comment by socoolbreeze** [comment]
Hi Ivan,

It works great!
Everything works with translation. Time sync worked, because I had it stil
on summertime for a few weeks and it changed. Als the voice assistant
prompt worked.

Only thing I noticed was that the old OBC temp order was sometimes (after
start, first 'boot') visible. So it is probably still somewhere in the code.

Thanks!!

Op di 1 nov. 2022 om 11:36 schreef Ivan Debnar ***@***.***>:

**Comment by nabucho** [comment]
Glad to hear. 
For the "temp order" - I am sure the order is never changed, and I have not modified it. What could be happening is that on "cold" start, the OIL temperature had not been yet reported by the engine management, so BB knows only about the 2 other temperatures ( like with common E46 with no oil temp at all ), and thus displays "Temp: ..." line. When the oil temp comes, it will  change to shorter format, so all three temps fit on display. Is this what you observed?

**Comment by socoolbreeze** [comment]
Hi It is sometimes on startup indeed. So I thought if you change the order
is wil do that also on startup. After one minute it stands in the new order.

greetz Ben




Op ma 7 nov. 2022 om 12:06 schreef Ivan Debnar ***@***.***>:
