### ISSUE TITLE
Add VR Toggle to BMBT and CD53

### ISSUE THREAD

**Issue by tedsalmon** [tedsalmon/BlueBus#13]
Allow voice recognition to be toggled like so:
- [ ] Via BMBT Phone Button
- [ ] Via CD53 "CD 3" double tap

**Comment by tedsalmon** [comment]
Completed in f933607844a28dfd694c58353369d435c63a0e4c

**Comment by harryberlin** [comment]
how did you got working the double tap for cd changing?

**Comment by tedsalmon** [comment]
@harryberlin,
> how did you got working the double tap for cd changing?

I have a timer, and I set a flag to store the "button press". If the second tap occurs within 500ms, then I consider it a double tap :)
