### ISSUE TITLE
Sudden strange behavior

### ISSUE THREAD

**Issue by Tom192** [tedsalmon/BlueBus#132]
Hi Ted,

for a few weeks now I have a strange problem that randomly my Bluebus seems to "crash" in some sort.
Almost every morning when I drive to work the music starts really late and sometimes I have to connect manually.
Autoplay sometimes also takes a long time to start.
Even with a new phone I got recently but then after a minute or so the radio switches to FM and I can no longer access my bluebus over the mode button. 
I have to unplug it once for it to work again. Otherwise it wont come back.

This problem is not occuring everyday but recently it was appearing more often.
I had Firmware 1.17 on it an upgraded it to the latest 1.18 in hope that this would help but unfortunately no change in this behavior.

Do you maybe have an idea what this could be?

My car is a 2001 E46 Coupe with MS43 (M54) and Business CD 53 if im not wrong.

Best regards!

Tom

**Comment by tedsalmon** [comment]
@Tom192 

Any chance you could shoot me an email? support@bluebus.dev 

Troubleshooting over GitHub issues is difficult. I would also recommend going up to version 1.3.0 https://t3ddftw.s3.us-east-2.amazonaws.com/BlueBus/firmware/bluebus_1_3_0.hex

:)

-Ted
