### ISSUE TITLE
Request: Volume indicator on Nav display

### ISSUE THREAD

**Issue by Ron199999** [tedsalmon/BlueBus#138]
Not sure if its possible, or if its relevant to other models (business CD player) but it would be great if upon a volume change the display could show a numeric value / GI of some sort that will show a volume level indication.

On my S2000 the radio will show 15/40 or 6/40
On my Honda Fit the radio will show xx/33 (along with a bar display)

The BMW has no indication for where the volume is, how loud it is, it just let you turn the knob.

**Comment by tedsalmon** [comment]
@Ron199999

Much as the display doesn't tell you where the volume is, the radio doesn't announce the current volume, or even the total available volume steps. So, without knowing where "zero" is, I can't tell you where you're at. The volume controls simply stipulate the direction of the volume control and how many "steps" to take (which increases as you spin the rotary knob).

Sorry!
-Ted
