### ISSUE TITLE
Autoplay Resumes after Connecting and then Pauses

### ISSUE THREAD

**Issue by mykekfz** [tedsalmon/BlueBus#15]
Hello Ted,

Auto play back seems to be buggy and works 5/10 with the latest update.

When you ignition is switched, it will resume as normal for about a few seconds and then pauses.
the user has to manually resume playback.

I was able to capture a log. 

[AUTORESUME NOT WORKING.txt](https://github.com/tedsalmon/BlueBus/files/3356858/AUTORESUME.NOT.WORKING.txt)

Regards,
Mike

**Comment by tedsalmon** [comment]
The offending code starts here: https://github.com/tedsalmon/BlueBus/blob/master/firmware/application/handler.c#L607

It appears that the MFL is asking for the Telephone status periodically, which is triggering this part of the code. I will have to find a better way to make use of the R/T button :).
