### ISSUE TITLE
Bluebus not playing any sound anymore

### ISSUE THREAD

**Issue by sven358** [tedsalmon/BlueBus#150]
Dear Ted,

I have been enjoying your product for a while now.
But the bluebus is no longer playing any music.

It happend before on a different e46, with another Phone and a older software update.

Now i got another e46 and the problem occurs again.
With another Phone and the latest software version.

Any ideas how i can solve this? Or might this be a hardware issue?

**Comment by tedsalmon** [comment]
@sven358 - Please email support@bluebus.dev about this :smile:
