### ISSUE TITLE
Updated Circuits

### ISSUE THREAD

**Issue by micro1995** [tedsalmon/BlueBus#155]
Are there any updated circuits available? 
I checked the circuits and noticed, that the eeprom in the version 2 circuits has the same size as in the version 1 circuits. 
Because of the updated Bootloader, this should cause issues.

**Comment by micro1995** [comment]
Thanks for uploading the V2.1 Circuit.
Do you have updated enclosure STLs as well?

Thanks
Alex

**Comment by tedsalmon** [comment]
@micro1995

I'll work on that. I do not have the STLs available off hand.

-Ted

**Comment by micro1995** [comment]
Thanks Ted for uploading the STLs as well.
