### ISSUE TITLE
Bluebus remains on when vehicle is off(E85). Firmware 1.3.2

### ISSUE THREAD

**Issue by HeresKenny** [tedsalmon/BlueBus#163]

**Comment by tedsalmon** [comment]
Hi!

Are you sure it’s not just the radio UI staying on for 60 seconds?

**Comment by HeresKenny** [comment]
The blue led on the device remains lit at all times, even after the vehicle has been off for over an hour.  If this is normal, then I guess all is well.

**Comment by tedsalmon** [comment]
@HeresKenny 

It turns on any time there’s bus traffic, so doors opening, unlocking via the fob. Are you testing by leaving the cargo door open and then walking away for a couple of minutes? Provide the key is out and the doors are closed, the BlueBus should sleep.

**Comment by HeresKenny** [comment]
Oh, ok.  I guess it is working just fine then.  Thank you for your quick replies.
