### ISSUE TITLE
Bluebus not switching off

### ISSUE THREAD

**Issue by dertimaushh** [tedsalmon/BlueBus#164]
![image](https://user-images.githubusercontent.com/73279374/232483904-920c8583-d92e-4c33-8a0a-be3669b815b5.jpeg)

Hi Ted,

I think I've found the root cause for my battery drainage. Bluebus isn't turning off. 

Everything works fine expect the fact it will not switch off.

Tried FW 1.30 and 1.32 now. 

Any thoughts? 

Best regards,
Tim

**Comment by tedsalmon** [comment]
@dertimaushh ,

Are you sure? With the keys out of the ignition and the doors closed, the LED on the BlueBus should go out within three to five minutes.

-Ted

**Comment by dertimaushh** [comment]
Yes, after some days of quiescent current measurement - I can confirm it's never turning off.

**Comment by tedsalmon** [comment]
@dertimaushh 

But is the LED going out? How much current is it pulling?

have you tried running the restore command? Auto off is controlled by a configuration byte.

-Ted

**Comment by dertimaushh** [comment]
~ 0,02-0,03A

Havn't tried any commands yet.

**Comment by dertimaushh** [comment]
![image](https://user-images.githubusercontent.com/73279374/232543505-540d39cd-b0c3-4a16-8743-3559fa02f754.jpeg)

Now let's wait.

**Comment by dertimaushh** [comment]
Success - restore solved the issue :-) 

![image](https://user-images.githubusercontent.com/73279374/232548790-115db87a-00b0-41e0-b47c-7122d679f2f7.jpeg)

**Comment by ShonkyCH** [comment]
> The Led stays on all the time.
> 
> ~ 0,02-0,03A
> 
If that's the total current measured (which it looks to be with the negative disconnected ie not the BlueBus alone) with the car asleep 20mA-30mA is well within spec (<40mA). For reference mine sits at about 19-20mA (with a sleeping BlueBus)

Seems like you've fixed a problem still.
