### ISSUE TITLE
BMW E46 Professional Radio Becker (CD54) Usage of Second Line of LCD

### ISSUE THREAD

**Issue by mbt28** [tedsalmon/BlueBus#165]
Hi,

Is it possible to make use of second line for button shortcuts? I mean instead of cd changer numbers, is it technically possible to change them as BMW e39 MID radio?

![image](https://user-images.githubusercontent.com/14265206/232745793-6305ab3a-5074-4f58-b693-21e6230103ff.png)
![image](https://user-images.githubusercontent.com/14265206/232747007-5f3e334f-3908-4a1d-aa27-2a7517dd6c82.png)
![image](https://user-images.githubusercontent.com/14265206/232746621-54b1073a-ab57-4221-8a1f-1543923afa7c.png)

https://www.youtube.com/watch?v=_ei-4o9-qeA

**Comment by tedsalmon** [comment]
Hello @mbt28!

No, this is unfortunately not possible. I have previously tried to make better use of the CD54 ample screen, but the developers didn't intend for any other modules to use the radio as an interface, unlike the MID whose sole purpose is just that :(.

Thanks!
-Ted
