### ISSUE TITLE
Aftermarket DSP Volume Control

### ISSUE THREAD

**Issue by Keff789** [tedsalmon/BlueBus#170]
Hello,

i would like to upgrade my sound system in my E46 and i am looking at amplifiers that have a digital input, as i understand that would allow me to directly connect the BlueBus to the DSP/Amplifier. Since the Amplifier has automatic input detection it may work pretty well until i realised that volume control will be an issue.

I have looked around the Code and i have found that there are some pieces of code that control the volume of the PCM 51xx in telephone mode if the Bluebus is set to DSP mode. So as i understand the bluebus notices if the volume knob is turned or the buttons on the steering wheels are pushed.  I am wondering if it would be possible to change the PCM volume not only in TEL mode but always and so control the Volume of the attached DSP. 

I would really like feedback and help and thanks a lot in advance!

**Comment by tedsalmon** [comment]
@Keff789

It is not possible to control the S/PDIF volume, unfortunately. How does the amp expect you to control volume on the digital interface?

-Ted

**Comment by Keff789** [comment]
oh okay :( 
I thought if Spdif is used in PCM mode i thought you have volume control and that the AMP would be able to use that. So i was in the perception that the "void PCM51XXSetVolume(unsigned char volume)" function would do exactly that. 

Thanks a lot anyways for your answer =)

**Comment by Keff789** [comment]
Oh okay :( 

i thought that in PCM Mode you could do volume control over SPDIF and that the amp would just use that. Than i have to look for antoher way, thanks anyways!
