### ISSUE TITLE
2005 LCI E46 CD43 W/ TAPE PLAYER AND MODE BUTTON

### ISSUE THREAD

**Issue by Benvlnt** [tedsalmon/BlueBus#172]
I have just received my BlueBus and plugged it in and it is simply saying CD 7-01, it will not work. Any ideas please?
I have put firmware backwards to 1.3 and it doesn't work still.
Please help :)

**Comment by tedsalmon** [comment]
If you just let the car go to sleep (5 minutes without the key in, and the doors closed), it'll start to work.

Thanks!
-Ted
