### ISSUE TITLE
BM53? Europe had the BM54

### ISSUE THREAD

**Issue by xXUnbekanntXx** [tedsalmon/BlueBus#178]
https://github.com/tedsalmon/BlueBus/blob/1bc7e2ae937bdfa3140a62cd753126c614bbea01/firmware/application/ui/bmbt.c#L70

I live in Europe does this line of code effect something? I mean I have the BM54 but if the bluebus is searching for a BM53 it will never find it.
Regards

**Comment by tedsalmon** [comment]
@xXUnbekanntXx - This isn’t a problem. The BM54 is just a BM53 with TP/TMC features. :)

**Comment by xXUnbekanntXx** [comment]
ok thanks. Then I dont know why I get the UART Error when checking "set log sys on". Could you help me with that one?
On my e39 I didnt even get a picture on the nav screen.

**Comment by tedsalmon** [comment]
> ok thanks. Then I dont know why I get the UART Error when checking "set log sys on". Could you help me with that one?
> On my e39 I didnt even get a picture on the nav screen.

This is normal when you reboot the unit. Are you seeing ibus traffic? Can you shoot me an email with pictures of the UI your car has?

**Comment by xXUnbekanntXx** [comment]
ok, I see the ibus traffic from the car side. The "get vin" com also works. I dont have a pic from my own nav screen right now, but basically it is this one. Split screen is active.
![images](https://github.com/tedsalmon/BlueBus/assets/35576254/200c0b5e-637a-4eb4-b2c7-906ff1dcbeb2)

**Comment by tedsalmon** [comment]
> ok, I see the ibus traffic from the car side. The "get vin" com also works. I dont have a pic from my own nav screen right now, but basically it is this one. Split screen is active. ![images](https://user-images.githubusercontent.com/35576254/271782612-200c0b5e-637a-4eb4-b2c7-906ff1dcbeb2.jpg)

That doesn't help, unfortunately. Is there not a "Bluetooth" or "CD 7-01" mode?

**Comment by xXUnbekanntXx** [comment]
No it’s not. Only when I connect the bmw cd changer.

**Comment by tedsalmon** [comment]
Can you shoot me over a log of the I-Bus traffic? https://github.com/tedsalmon/BlueBus/wiki/Gathering-a-Log

**Comment by xXUnbekanntXx** [comment]
[bluebus log.txt](https://github.com/tedsalmon/BlueBus/files/12775330/bluebus.log.txt)
thats it.

**Comment by tedsalmon** [comment]
> [bluebus log.txt](https://github.com/tedsalmon/BlueBus/files/12775330/bluebus.log.txt) thats it.

Did you build this unit yourself or get it from me? I would guess that there is a loose pin on the I-Bus transciever based on the amount of General and Frame errors in the logs.

**Comment by xXUnbekanntXx** [comment]
I bought a e39 and it was inside. The owner told me that it worked but after a while it stopped. 
Is there a specific pin I could check?

**Comment by tedsalmon** [comment]
@xXUnbekanntXx 

Could you please send me pictures of the circuit board? support -at- bluebus -dot- dev

**Comment by xXUnbekanntXx** [comment]
![IMG_0433](https://github.com/tedsalmon/BlueBus/assets/35576254/6fa44ae0-fa3c-4d71-b658-8b1e71c2f0da)
Should I send it to you via Email?

**Comment by tedsalmon** [comment]
> ![IMG_0433](https://user-images.githubusercontent.com/35576254/271923517-6fa44ae0-fa3c-4d71-b658-8b1e71c2f0da.jpg) Should I send it to you via Email?

Please shoot me an email so we can talk about getting it repaired :)
