### ISSUE TITLE
Mini R53 with HK and GPS

### ISSUE THREAD

**Issue by Sill1000** [tedsalmon/BlueBus#179]
Hello 
I connected the interface on the Ibus and 12V. The radio start correctly but no sound and the GPS screen stay black!
Blinkers are not working anymore
If I disconnect the interface, the sound and the GPS screen are back and work fine. What to do ?
Of course I tried many reset. 
thanks

**Comment by tedsalmon** [comment]
Closing issue. OP wired the I/K-Bus and GND pin backwards as this was a "self-install" with no pre-wiring.
