### ISSUE TITLE
E39 Navigation metadata is not complete and appears like a menu

### ISSUE THREAD

**Issue by StefPedro** [tedsalmon/BlueBus#182]
I have an issue with the dashboard, in the sense that it dosen't show the entire song name, album, artist if their lenght is too big. Also, it dosen't look the same as Ryan's form E39 Source, and others i found online. It looks like a selectable menu. Also, the temp readouts sometimes don't show up.
The car is a European 1999 E39 with retrofitted original navigation. MK3 computer,TV, BM54 and HiFi.
This is my car (sorry for the crappy picture):
![WhatsApp Image 2023-11-24 at 2 23 23 AM](https://github.com/tedsalmon/BlueBus/assets/64042183/b67c63d5-57d3-4cce-8d83-77f8f5a3cf36)
Here's a picture  i found online on how it looks:
![image](https://github.com/tedsalmon/BlueBus/assets/64042183/6281b2e7-00fd-4a5f-b962-133069895b2d)

**Comment by tedsalmon** [comment]
It looks like your Nav doesn’t support static display mode, which isn’t uncommon as it was only available on the MKIV Nav with late software revision.

Could you supply a picture of your Settings menu? The Navi one, not the BlueBus one.

-Ted

**Comment by StefPedro** [comment]
I have the MK3 nav, with its latest software (3-1/63)(V23), that might explain why it's not working that way, and might motivate me to buy a MK4. Thanks for the info!
![WhatsApp Image 2023-11-24 at 2 51 11 AM](https://github.com/tedsalmon/BlueBus/assets/64042183/0fd82b6b-d4d4-4721-8ea4-b8782f4a0b4f)

**Comment by tedsalmon** [comment]
> I have the MK3 nav, with its latest software (3-1/63)(V23), that might explain why it's not working that way, and might motivate me to buy a MK4. Thanks for the info! Settings menu pictures will come tomorrow, since it's night time in Europe. ![WhatsApp Image 2023-11-24 at 2 51 11 AM](https://user-images.githubusercontent.com/64042183/285328718-0fd82b6b-d4d4-4721-8ea4-b8782f4a0b4f.jpeg)


If you know it's a MKIII unit, then that is the answer I was looking for :). I believe v27 (1/70) is where they added the static display mode, which was implemented to allow the MP3 capable CD Changer to display ID3 tags.

Thanks!
-Ted

**Comment by StefPedro** [comment]
> > I have the MK3 nav, with its latest software (3-1/63)(V23), that might explain why it's not working that way, and might motivate me to buy a MK4. Thanks for the info! Settings menu pictures will come tomorrow, since it's night time in Europe. ![WhatsApp Image 2023-11-24 at 2 51 11 AM](https://user-images.githubusercontent.com/64042183/285328718-0fd82b6b-d4d4-4721-8ea4-b8782f4a0b4f.jpeg)
> 
> 
> 
> 
> 
> If you know it's a MKIII unit, then that is the answer I was looking for :). I believe v27 (1/70) is where they added the static display mode, which was implemented to allow the MP3 capable CD Changer to display ID3 tags.
> 
> 
> 
> Thanks!
> 
> -Ted

Ok, thanks for the info, I am getting a MK4 next week, excited for newer maps, perspective and the metadata showing properly. I love the BlueBus so far!
