### ISSUE TITLE
Navigation MKIV does not properly display metadata

### ISSUE THREAD

**Issue by FQuimson23** [tedsalmon/BlueBus#195]
I'm having an issue with the metadata on an MKIV system appearing as it did when I had an MKIII System in previously. The radio in FM also displays correctly but not on Bluetooth. I'm not sure if this will affect anything, but I did swap out my original BM53 radio for a Siemens unit out of an X3 since the radio amplifier seemed to be on its way out.

The vehicle is an E39 Prod Date 01/02 with MKIV upgraded to latest version. I can get the P/N from the radio unit if it's needed. 
![20240224_085947](https://github.com/tedsalmon/BlueBus/assets/8144883/83da4bd1-82b2-4d08-9eff-b1b1384877b4)
![20240224_085934](https://github.com/tedsalmon/BlueBus/assets/8144883/02caef4a-be0d-4dc7-9df1-e390b9f63250)
![20240224_085903](https://github.com/tedsalmon/BlueBus/assets/8144883/f5a8cbbd-1b2c-41ed-ba06-7c9633a8be06)

**Comment by FQuimson23** [comment]
Yeah I might’ve thought it was a little confusing, but that’s the metadata from the radio station on the last picture. Metadata from Bluetooth mode itself is like it is in the first picture, displayed as if I still had the MKIII. 

I included the radio station metadata picture just to show that the function was working on another mode.

**Comment by tedsalmon** [comment]
@FQuimson23,

Ah! Damn, I need to source one of the HD Siemens radios -- I didn't know they implemented the static UI for radio metadata! If you access the CLI, you can get the static UI by running this command:

```
set ui 6
```
Here's the relevant code: https://github.com/tedsalmon/BlueBus/blob/master/firmware/application/ui/cli.c#L681

Thanks!
-Ted

**Comment by tedsalmon** [comment]
@FQuimson23,

Are we all good here? :)

-Ted

**Comment by FQuimson23** [comment]
I haven't been able to test since my E39 decided that it wanted to leak coolant everywhere the day I posted this issue.

Anyways, I'll attach a picture of some P/N and prod. dates that may help you source a Siemens radio with metadata and/or HD Radio capabilities. :) 
![IMG_3087](https://github.com/tedsalmon/BlueBus/assets/8144883/9c36d5ab-e03c-4c7b-ba9f-69f0698c686d)

**Comment by tedsalmon** [comment]
@FQuimson23

Ah yes, it's just marking its territory :)

Thanks for the screenshot!

-Ted

**Comment by FQuimson23** [comment]
Looks like it's all good to go! Finally had some time to get the radiator replaced for the leak and setting the UI to 6 worked. 

![20240330_082703](https://github.com/tedsalmon/BlueBus/assets/8144883/30bef3b9-3935-437f-aa06-9023753ba09c)
