### ISSUE TITLE
[BMW Z4 E85] pressing "mode" button yields "No Disc" message

### ISSUE THREAD

**Issue by AndrijaLFC** [tedsalmon/BlueBus#202]
Hi!

I have bluebus in my bmw Z4 E85 (2004) set up and it's been working fine until Saturday, when I just get "No Disc" message. I checked bluebus to see if cables are connected properly, and everything seems fine. I can connect to bluebus Bluetooth, but the car <-> bluebus connection is not happening.

**Comment by tedsalmon** [comment]
@AndrijaLFC,
Have you disconnected the unit from the car and reconnected it?

Thanks!
-Ted

**Comment by AndrijaLFC** [comment]
Hi Ted,

Thanks for prompt response!
Disconnecting and reconnecting fixed the issue!

Thank you!
