### ISSUE TITLE
E39 blubus pairing 

### ISSUE THREAD

**Issue by COOPERSPORT1** [tedsalmon/BlueBus#204]
Not a complete technophobe but not brilliant  either! Picked up my E39 with blubus via CD cables yesterday, previous owner unpaired his iPhone, however my Samsung will not find it as a Bluetooth device.

Left overnight still no joy, unplugged for 20mins still no good.

What's the remedy?

**Comment by tedsalmon** [comment]
Did you enable Pairing @COOPERSPORT1 ? :)

**Comment by COOPERSPORT1** [comment]
OK actually I take it back, I am a techno biff, how do I do that?

**Comment by tedsalmon** [comment]
@COOPERSPORT1,

Do you have Nav or not?

**Comment by COOPERSPORT1** [comment]
No nav

**Comment by COOPERSPORT1** [comment]
No nav

**Comment by tedsalmon** [comment]
@COOPERSPORT1

Is this a US car? If so, you should just have a "PAIR" button on the bottom row of the MID.

**Comment by COOPERSPORT1** [comment]
No it's a UK 2003 525d touring. Assuming I need to plug in with my laptop and enable something?

**Comment by tedsalmon** [comment]
@COOPERSPORT1,

Can post a picture of your radio, please? If it has a physical "6" button, you can hit that to enable pairing.

-Ted

**Comment by COOPERSPORT1** [comment]
Bingo that worked, guess if you don't know you don't know!
Will it pair to 2 phones simultaneously or is that asking a bit much?

**Comment by COOPERSPORT1** [comment]
![17187196440623938845989608665991](https://github.com/tedsalmon/BlueBus/assets/173164616/c0519f49-c981-40fd-a337-f3abde3af99b)

**Comment by COOPERSPORT1** [comment]
Although found and connected it seems to keep dropping the connection

**Comment by tedsalmon** [comment]
@COOPERSPORT1

You have an IRIS rather than a MID which means you don't have a UI either. Shoot me an email, please -- support@bluebus.dev
