### ISSUE TITLE
Audio issues during phone call

### ISSUE THREAD

**Issue by archonauto** [tedsalmon/BlueBus#206]
Hardware 2.0 (serial 3743) Firmware 1.3.4, CD53 in 2003 Z4 (E85) with Carver audio. Mic gain set to 8db.

Having a couple of issues:

1) When call mode is set to "default", no audio plays through the speakers of the car during the call. Had this same issue on firmware 1.3.3, went away when I downgraded to 1.3.0, but returned when I updated to 1.3.4.  If I set call mode "TCU" or "No Mute", the call audio plays, but there are other issues that would prevent me from using them such as no ability to control the volume of the call audio and voice quality is terrible for the other person with many clicks and noise even when the car is parked inside a garage with the engine off. Voice quality is quite clear with no clicking noises for the other person when call mode is set to "default" but then I have no audio.
> Update to this: after tearing the car apart, tracing all the telephone wiring, and testing everything, it appears the bluebus isn’t outputting anything on the tel+ and tel- lines in default mode. Multimeter shows voltage output in “TCU” and “no mute” but reads 0 in default.

2) If call volume offset is set to 14 or 15 (in "default" call mode), the offset stays applied after the call ends and the music resumes at a much louder level. and the volume knob can't turn the volume all the way to zero because the offset is still applied. Turning the radio off and back on resets this. Doesn't seem to happen if the offset is set below 14.

3) the “3” button on the radio doesn’t seem to do anything in terms of answering calls, ending calls, or activating Siri by double-pressing it

**Comment by archonauto** [comment]
After a bit of inspection on my car, it’s looking like issue 1 might not actually be a bluebus problem. I’ve been checking the wiring diagrams for the car and following the harness. The bluebus connects to the car’s 54-pin connector, which in turn feeds to the 12 pin phone prep connector in the car’s harness at the bulkhead. Looks like “tel mute”, “tel on”, “tel out +” and “tel out -“ should all run from that connector to the CD53 head unit but “tel mute” is the only one that seems to actually be at the head unit. Looks like I’ll have to run wires for the other 3 (or find the missing ones bundles somewhere in the dash?) and see what happens

**Comment by tedsalmon** [comment]
@archonauto,

I think we got most of this solved over email, right? I definitely need to look at issue 3 still, though.

-Ted

**Comment by archonauto** [comment]
> @archonauto,
> 
> I think we got most of this solved over email, right? I definitely need to look at issue 3 still, though.
> 
> -Ted

Thanks Ted. I’ve been meaning to follow up with you for a while now so I just replied to the email again. The important bits (issue 1) seem to be sorted out now between the firmware you sent me and a 338 microphone. Issue 2 was still there but doesn’t actually affect me since I don’t run the volume offset high enough to trigger it. So it’s really just issue 3  and the comfort blinker glitches that still remain.

**Comment by chicodorosario** [comment]
I have the same issue as mentioned above with issue 1. I installed my newly acquired OEM microphone and doing test calls and it's as mentioned above in default, TCU or even in no mute. 

Please advise

**Comment by tedsalmon** [comment]
> I have the same issue as mentioned above with issue 1. I installed my newly acquired OEM microphone and doing test calls and it's as mentioned above in default, TCU or even in no mute.
> 
> Please advise

Can you shoot me an email, please? It's *so much* easier to keep track of issues there! It makes sense that "Default" call mode doesn't work for you though, as I recall you had the DSP amplifier in your Touring.

Thanks!
-Ted
