### ISSUE TITLE
Cd53 microphone volume

### ISSUE THREAD

**Issue by chrishobo** [tedsalmon/BlueBus#21]
Users are intermittently reporting low outgoing volume.  Likely a steady problem, but some users do not complain so microphone is partially working.

Microphone is 84318380338
Head unit is  65. 12-6 961 215 

Late head unit is retrofitted into an early (3/01) wagon.

**Comment by tedsalmon** [comment]
@chrishobo,

Sorry for the lag -- I don't usually check GitHub issues (try me via email at support at bluebus.dev).

Sounds like you may need to make use of cVc, which can be done via this firmware version: https://t3ddftw.s3.us-east-2.amazonaws.com/BlueBus/bluebus_1_1_8_3.hex

You can find the firmware upgrade instructions here: https://github.com/tedsalmon/BlueBus/wiki/Firmware-Upgrade

Thanks!
-Ted
