### ISSUE TITLE
(Feature request) Cyrillic symbols support

### ISSUE THREAD

**Issue by AlexeyPribytkin** [tedsalmon/BlueBus#25]
Any metadata with Cyrillic symbols is displayed as Unknown Artist/Title/Album.
It would be great to have proper support for this.

**Comment by tedsalmon** [comment]
Hey @AlexeyPribytkin,

Unfortunately, the BMW system only supports extended ASCII, which does not include Cyrillic characters. There's nothing I can do to improve this :(

-Ted
