### ISSUE TITLE
[CD53] Manual mode does not work

### ISSUE THREAD

**Issue by dutchhome** [tedsalmon/BlueBus#3]
When switching to manual mode (pressing the "m" button between the prev / next buttons), the prev / next buttons should switch to rewind / fast forward.  Instead of passing these commands to the bluetooth device, the buttons are non-functional.  Manual mode must be turned off in order for prev / next to work again.

**Comment by tedsalmon** [comment]
@dutchhome,

Thanks for the report! The BC127 doesn't have "seek" functionality, unfortunately. I will see what the CD53 broadcasts over the IBus when set to manual mode (I had no idea what the M button was for, as I've only ever had E46s with the nav) and continue using those for Prev / Next.

Thanks!
-Ted

**Comment by dutchhome** [comment]
According to this site, it seems to support it:

https://learn.sparkfun.com/tutorials/understanding-the-bc127-bluetooth-module/all

> A2DP is a two-channel audio streaming protocol, which transfers data from a source to a sink. The source can be a cell phone, a media player, or the audio input on another BC127 (or similar) module. AVRCP allows the BC127 to send commands to the remote device which will cause the remote device to play, pause, stop, advance or reverse playback; some remote devices will transmit track meta data back to the BC127 via the AVRCP protocol.
> 
> The BC127 also supports the Hands-Free Protocol (HFP); we’ll talk about that later, but for now be aware that incoming calls over the HFP connection will override data on the A2DP connection.
> 
> Here are the commands you’ll need to know to get A2DP and AVRCP working properly:
> 
> MUSIC instruction sends a command over the AVRCP link to the A2DP source device. Valid options for instruction are PLAY, PAUSE, STOP, FORWARD and BACKWARD.

**Comment by dutchhome** [comment]
Sorry, I see what you mean now. Clearly I misread that section. By forward and backward it does seem that they mean next track and previous track. Yes, next track / previous track would still be preferable to non functioning buttons.

**Comment by tedsalmon** [comment]
@dutchhome,

_Actually_, it looks like you're right! As of Melody 7.x, there's `FF_PRESS`, `FF_RELEASE` and `REW_PRESS`, `REW_RELEASE` commands.

![screenshot_20190216_182847](https://user-images.githubusercontent.com/4956562/52907569-09b5ee80-3219-11e9-9563-2a5808730de3.png)
I'll have to see how the radio signals these actions to the CDC to make sure the implementation will work, but it looks solid for now.

Thanks!
-Ted

**Comment by tedsalmon** [comment]
@dutchhome,

This has been implemented in firmware v1.0.1 but I have noticed that at least on my Pixel 3, the seek actions have no effect on playback. As more people continue to test, I will see if this is the case for most people and simply ignore manual mode and re-implement this as Next / Previous, rather than seek.

Thanks!
-Ted
