### ISSUE TITLE
[CD53] Random mode does not work

### ISSUE THREAD

**Issue by dutchhome** [tedsalmon/BlueBus#4]
If random mode is entered (RND button), the prev / next buttons no longer work.  It is also not possible to exit random mode by pressing the button again.  A workaround is to turn the radio off and back on or otherwise exit and reenter CDC mode.

**Comment by tedsalmon** [comment]
@dutchhome,

Sounds like it's sending a different message, then. I will monitor the IBus messages between the CDC and Radio to see what's up.

Thanks!
-Ted

**Comment by tedsalmon** [comment]
@dutchhome,

This has been resolved. Random mode now has no impact on the BlueBus device.

Thanks!
-Ted
