### ISSUE TITLE
Video Modul 16:9 Screen override 

### ISSUE THREAD

**Issue by dertimaushh** [tedsalmon/BlueBus#43]
Hi Ted, 

i've realized that Bluebus overrides the signal of my TV Modul.  I'd like to use the TV Modul to connect it to an CarPlay adapter and use the Bluebus Bluetooth connection for Voice Controls and Audio. This would be the perfect 2021 tech update while maintaining the 100% OEM look.  

In reverse it works fine and my camera overrides the screen as designed. 

The setup in my 2001 E38: BM54 / Bluebus / 16:9  / MK4  / TV-Modul / Reverse Camera 

Any thoughts on this?

Best regards,
Tim

**Comment by tedsalmon** [comment]
Tim,

Would it be possible for you to provide a log (https://github.com/tedsalmon/BlueBus/wiki/Gathering-a-Log) of the BlueBus overriding the TV Module? It would also be useful to see a video of what you're describing.

I suspect I'm simply not listening to a specific I-Bus message notifying the system that the TV Module is active. We didn't get the TV module here in the U.S., so it's not something I'm very familiar with.

Thanks!
-Ted

**Comment by dertimaushh** [comment]
Hi Ted,

Here is the log:
[bluebus.txt](https://github.com/tedsalmon/BlueBus/files/5441301/bluebus.txt)

On video:
Without Bluebus:
https://youtu.be/c_i9hbMeLc8
With Bluebus:
https://youtu.be/KlGnF2iGF6c

Many thanks,
Tim

**Comment by harryberlin** [comment]
GT tells the Radio
3B 05 68 4E 01 00 19: TV MODE ON
3B 05 68 4E 00 00 18: TV MODE OFF

**Comment by dertimaushh** [comment]
That's great - i can see 3B 05 68 4E 01 00 19 twice in the Log - because i've tried it twice :-)

**Comment by piersholt** [comment]
@dertimaushh 

Sounds like my kind of crazy! 😄  How on earth do you get a CarPlay adapter output a suitable video signal?

**Comment by dertimaushh** [comment]
The are some Apple carplay interfaces out there with AV / RGB Output which i've seen working on the 16:9.  But 1st Bluebus should stop overwriting the screen in TV Mode :-) 

E.g. SUNE TECH Wirless Apple Carplay & Android Auto Box with USB player / Music / BT

**Comment by harryberlin** [comment]
> That's great - i can see 3B 05 68 4E 01 00 19 twice in the Log - because i've tried it twice :-)

you can't do nothing. just wait for update.
that's a bug of bluebus. the messages are required to solve the problem.

**Comment by dertimaushh** [comment]
> you can't do nothing. just wait for update.
> that's a bug of bluebus. the messages are required to solve the problem.

I know - I was just excited about the fact that my logging worked.

**Comment by piersholt** [comment]
@dertimaushh 

> The are some Apple carplay interfaces out there with AV / RGB Output which i've seen working on the 16:9. 

Ahah, who knew!?

> I know - I was just excited about the fact that my logging worked.

Thanks for taking the time to do the logging, not to mention the videos. It's a huge help.

> But 1st Bluebus should stop overwriting the screen in TV Mode :-)

It's in the pipeline 😊

**Comment by tedsalmon** [comment]
@dertimaushh,

Please try this firmware: https://t3ddftw.s3.us-east-2.amazonaws.com/BlueBus/firmware/bluebus_1_1_16_2.hex

Thanks!
-Ted

**Comment by dertimaushh** [comment]
Almost same result: https://youtu.be/ddkMxfc9Cy4

But while driving the TV Waring while driving message stayed occasionally when I hit the view toogle button several times. 

So some progress :-)

Best regards,
Tim

**Comment by tedsalmon** [comment]
@dertimaushh 

Try this: https://t3ddftw.s3.us-east-2.amazonaws.com/BlueBus/firmware/bluebus_1_1_16_5.hex

Thanks!
-Ted

**Comment by dertimaushh** [comment]
![image](https://user-images.githubusercontent.com/73279374/98592182-a82d9180-22d1-11eb-88a9-cd66bfa6d6b7.jpeg)

It's working!!!! Many thanks.

Next question - not Bluebus related: How can I keep the Bluetooth Audio connection alive when switching to TV Mode?!

**Comment by tedsalmon** [comment]
@dertimaushh,

I don't think that's possible. The `3B 05 68 4E 01 00 19` message tells the radio to switch audio inputs as well as "stopping" the CD Changer. It should resume when you exit TV mode, though.

Thanks!
-Ted

**Comment by dertimaushh** [comment]
Yes it resumes when I exit TV mode. 

Guess it's not possible havin TV mode without that bit (3B 05 68 4E 01 00 19)?

**Comment by tedsalmon** [comment]
@dertimaushh 

Issuing the inverse of `4E` (`0x00` rather than `0x01) will result in the radio writing to the GT again, and therefore booting you from TV mode anyways (similarly to the initial bug reported here). If you had the DSP Amplifier, I could trick the DSP into using the S/PDIF input rather than analog, but based on your YT videos, this vehicle doesn't have DSP :(.

-Ted

**Comment by dertimaushh** [comment]
No, no Dsp. That's an other upgrade  😄

I think I'll have to work with the GPIO-Pin 7 of TV-Module as the Raspberry does.

**Comment by tedsalmon** [comment]
This has been resolved for some time now :)
