### ISSUE TITLE
Retrofit Functionality to the CD53 UI

### ISSUE THREAD

**Issue by tabor-a** [tedsalmon/BlueBus#46]
1.  Add door locking functionality to the current unlocking functionality.

2.  Display inbound caller ID.

3.  Find a place to display coolant temp?

**Comment by tedsalmon** [comment]
Yeah, I've been meaning to do this, but it's just a royal pain in the if/else. If I did it right, I would have to refactor the way all menus work, which would take even longer.

**Comment by tedsalmon** [comment]
This has been completed as of `1.3.0`
