### ISSUE TITLE
Current Firmware Release link on Wiki Firmware Upgrade page

### ISSUE THREAD

**Issue by tabor-a** [tedsalmon/BlueBus#49]
Add a link to the Firmware current release download *OR* the repository of all firmware releases on the Wiki Firmware Upgrade page in addition to the Firmware Update Tool.

**Comment by tedsalmon** [comment]
@tabor-a 

Listing the software versions is on my radar already, but I'm not going to put it in the Wiki because hardly anyone comes to GitHub or understands how to navigate it. I'm just going to make a `/software` or something on the BlueBus website.

Thanks!
-Ted

**Comment by tabor-a** [comment]
That would also do it!

**Comment by tabor-a** [comment]
Thanks, Ted!  Software (Firmware) page looks great.  On the Installation page, there's a typo "Instalation" at the top...

**Comment by tedsalmon** [comment]
Thanks, @tabor-a -- fixed!
