### ISSUE TITLE
No menu displayed after connecting

### ISSUE THREAD

**Issue by decimity** [tedsalmon/BlueBus#60]
After installing, the bluebus displayed as "CDC 7-01" on the board monitor (no nav), none of the buttons were operable and therefore I could not get it to pair with the phone.
![image](https://user-images.githubusercontent.com/76714210/103257792-aa58c600-49cd-11eb-9487-730875d95a11.jpeg)

Tried connecting the bluebus to both PC and Mac and could not get the device to connect (green LED on)

Any help appreciated :)

**Comment by tedsalmon** [comment]
As mentioned via E-mail, a VM only set up is rather odd in my experience, so the BlueBus doesn't account for it. Manually running `set ui 2` resolves the issue.

Thanks!
-Ted
