### ISSUE TITLE
(Question) Does telephone module (TCU) is required to enable hands free protocol?

### ISSUE THREAD

**Issue by vgergiev** [tedsalmon/BlueBus#61]
Would HFP working properly if I will connect an external microphone to the bluebus without connecting anything to the bluebus telephone connector?
Working properly - sound goes via car stereo and voice captured by the external microphone

**Comment by tedsalmon** [comment]
Yes! You'll need to make these changes for a non-OE Microphone:

```
bt mpreamp on
bt mgain d2
```

:)

-Ted
