### ISSUE TITLE
One way audio on phone calls

### ISSUE THREAD

**Issue by orlandwright** [tedsalmon/BlueBus#78]
Initially it was no-way audio. Installed telephony license per instructions and now receive audio but far end hears no audio from me, just a faint buzzing noise. Car is equipped with microphone. 2006 M3. Also reflashed to 1.1.17 with no change in behavior.

**Comment by tedsalmon** [comment]
@orlandwright 

Are you sure you have a microphone? Can you get the part number, please?

**Comment by tedsalmon** [comment]
Closing this for lack of follow up. If you're still having issues, please email me at support@bluebus.dev :)
